# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import deploy.protos.motion_control_pb2 as motion__control__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ecatplat_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class EcatplatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArmConfig = channel.unary_unary(
                '/droidgrpc.EcatplatService/GetArmConfig',
                request_serializer=motion__control__pb2.Empty.SerializeToString,
                response_deserializer=motion__control__pb2.DroidConfigs.FromString,
                _registered_method=True)
        self.GetLegConfig = channel.unary_unary(
                '/droidgrpc.EcatplatService/GetLegConfig',
                request_serializer=motion__control__pb2.Empty.SerializeToString,
                response_deserializer=motion__control__pb2.DroidConfigs.FromString,
                _registered_method=True)
        self.GetRobotConfig = channel.unary_unary(
                '/droidgrpc.EcatplatService/GetRobotConfig',
                request_serializer=motion__control__pb2.Empty.SerializeToString,
                response_deserializer=motion__control__pb2.DroidConfigs.FromString,
                _registered_method=True)
        self.GetArmState = channel.unary_unary(
                '/droidgrpc.EcatplatService/GetArmState',
                request_serializer=motion__control__pb2.Empty.SerializeToString,
                response_deserializer=motion__control__pb2.DroidStateResponse.FromString,
                _registered_method=True)
        self.GetLegState = channel.unary_unary(
                '/droidgrpc.EcatplatService/GetLegState',
                request_serializer=motion__control__pb2.Empty.SerializeToString,
                response_deserializer=motion__control__pb2.DroidStateResponse.FromString,
                _registered_method=True)
        self.GetRobotState = channel.unary_unary(
                '/droidgrpc.EcatplatService/GetRobotState',
                request_serializer=motion__control__pb2.Empty.SerializeToString,
                response_deserializer=motion__control__pb2.DroidStateResponse.FromString,
                _registered_method=True)
        self.GetArmStateStream = channel.unary_stream(
                '/droidgrpc.EcatplatService/GetArmStateStream',
                request_serializer=motion__control__pb2.Empty.SerializeToString,
                response_deserializer=motion__control__pb2.DroidStateResponse.FromString,
                _registered_method=True)
        self.GetLegStateStream = channel.unary_stream(
                '/droidgrpc.EcatplatService/GetLegStateStream',
                request_serializer=motion__control__pb2.Empty.SerializeToString,
                response_deserializer=motion__control__pb2.DroidStateResponse.FromString,
                _registered_method=True)
        self.GetRobotStateStream = channel.unary_stream(
                '/droidgrpc.EcatplatService/GetRobotStateStream',
                request_serializer=motion__control__pb2.Empty.SerializeToString,
                response_deserializer=motion__control__pb2.DroidStateResponse.FromString,
                _registered_method=True)
        self.SetArmCommand = channel.unary_unary(
                '/droidgrpc.EcatplatService/SetArmCommand',
                request_serializer=motion__control__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=motion__control__pb2.Empty.FromString,
                _registered_method=True)
        self.SetLegCommand = channel.unary_unary(
                '/droidgrpc.EcatplatService/SetLegCommand',
                request_serializer=motion__control__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=motion__control__pb2.Empty.FromString,
                _registered_method=True)
        self.SetRobotCommand = channel.unary_unary(
                '/droidgrpc.EcatplatService/SetRobotCommand',
                request_serializer=motion__control__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=motion__control__pb2.Empty.FromString,
                _registered_method=True)
        self.SetArmCommandStream = channel.stream_unary(
                '/droidgrpc.EcatplatService/SetArmCommandStream',
                request_serializer=motion__control__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=motion__control__pb2.Empty.FromString,
                _registered_method=True)
        self.SetLegCommandStream = channel.stream_unary(
                '/droidgrpc.EcatplatService/SetLegCommandStream',
                request_serializer=motion__control__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=motion__control__pb2.Empty.FromString,
                _registered_method=True)
        self.SetRobotCommandStream = channel.stream_unary(
                '/droidgrpc.EcatplatService/SetRobotCommandStream',
                request_serializer=motion__control__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=motion__control__pb2.Empty.FromString,
                _registered_method=True)
        self.ExchangeArmControlStream = channel.stream_stream(
                '/droidgrpc.EcatplatService/ExchangeArmControlStream',
                request_serializer=motion__control__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=motion__control__pb2.DroidStateResponse.FromString,
                _registered_method=True)
        self.ExchangeLegControlStream = channel.stream_stream(
                '/droidgrpc.EcatplatService/ExchangeLegControlStream',
                request_serializer=motion__control__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=motion__control__pb2.DroidStateResponse.FromString,
                _registered_method=True)
        self.ExchangeRobotControlStream = channel.stream_stream(
                '/droidgrpc.EcatplatService/ExchangeRobotControlStream',
                request_serializer=motion__control__pb2.DroidCommandRequest.SerializeToString,
                response_deserializer=motion__control__pb2.DroidStateResponse.FromString,
                _registered_method=True)


class EcatplatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetArmConfig(self, request, context):
        """Get robot config information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLegConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArmState(self, request, context):
        """Get robot state information (such as kinematic state, power state, or faults).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLegState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArmStateStream(self, request, context):
        """Lightweight Streaming version of RobotState
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLegStateStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotStateStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetArmCommand(self, request, context):
        """Command updates for joint control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLegCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRobotCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetArmCommandStream(self, request_iterator, context):
        """Command updates for joint control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLegCommandStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRobotCommandStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeArmControlStream(self, request_iterator, context):
        """Robot State and Command updates for robot control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeLegControlStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeRobotControlStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EcatplatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetArmConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArmConfig,
                    request_deserializer=motion__control__pb2.Empty.FromString,
                    response_serializer=motion__control__pb2.DroidConfigs.SerializeToString,
            ),
            'GetLegConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLegConfig,
                    request_deserializer=motion__control__pb2.Empty.FromString,
                    response_serializer=motion__control__pb2.DroidConfigs.SerializeToString,
            ),
            'GetRobotConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotConfig,
                    request_deserializer=motion__control__pb2.Empty.FromString,
                    response_serializer=motion__control__pb2.DroidConfigs.SerializeToString,
            ),
            'GetArmState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArmState,
                    request_deserializer=motion__control__pb2.Empty.FromString,
                    response_serializer=motion__control__pb2.DroidStateResponse.SerializeToString,
            ),
            'GetLegState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLegState,
                    request_deserializer=motion__control__pb2.Empty.FromString,
                    response_serializer=motion__control__pb2.DroidStateResponse.SerializeToString,
            ),
            'GetRobotState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotState,
                    request_deserializer=motion__control__pb2.Empty.FromString,
                    response_serializer=motion__control__pb2.DroidStateResponse.SerializeToString,
            ),
            'GetArmStateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetArmStateStream,
                    request_deserializer=motion__control__pb2.Empty.FromString,
                    response_serializer=motion__control__pb2.DroidStateResponse.SerializeToString,
            ),
            'GetLegStateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLegStateStream,
                    request_deserializer=motion__control__pb2.Empty.FromString,
                    response_serializer=motion__control__pb2.DroidStateResponse.SerializeToString,
            ),
            'GetRobotStateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRobotStateStream,
                    request_deserializer=motion__control__pb2.Empty.FromString,
                    response_serializer=motion__control__pb2.DroidStateResponse.SerializeToString,
            ),
            'SetArmCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SetArmCommand,
                    request_deserializer=motion__control__pb2.DroidCommandRequest.FromString,
                    response_serializer=motion__control__pb2.Empty.SerializeToString,
            ),
            'SetLegCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLegCommand,
                    request_deserializer=motion__control__pb2.DroidCommandRequest.FromString,
                    response_serializer=motion__control__pb2.Empty.SerializeToString,
            ),
            'SetRobotCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRobotCommand,
                    request_deserializer=motion__control__pb2.DroidCommandRequest.FromString,
                    response_serializer=motion__control__pb2.Empty.SerializeToString,
            ),
            'SetArmCommandStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SetArmCommandStream,
                    request_deserializer=motion__control__pb2.DroidCommandRequest.FromString,
                    response_serializer=motion__control__pb2.Empty.SerializeToString,
            ),
            'SetLegCommandStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SetLegCommandStream,
                    request_deserializer=motion__control__pb2.DroidCommandRequest.FromString,
                    response_serializer=motion__control__pb2.Empty.SerializeToString,
            ),
            'SetRobotCommandStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SetRobotCommandStream,
                    request_deserializer=motion__control__pb2.DroidCommandRequest.FromString,
                    response_serializer=motion__control__pb2.Empty.SerializeToString,
            ),
            'ExchangeArmControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ExchangeArmControlStream,
                    request_deserializer=motion__control__pb2.DroidCommandRequest.FromString,
                    response_serializer=motion__control__pb2.DroidStateResponse.SerializeToString,
            ),
            'ExchangeLegControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ExchangeLegControlStream,
                    request_deserializer=motion__control__pb2.DroidCommandRequest.FromString,
                    response_serializer=motion__control__pb2.DroidStateResponse.SerializeToString,
            ),
            'ExchangeRobotControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ExchangeRobotControlStream,
                    request_deserializer=motion__control__pb2.DroidCommandRequest.FromString,
                    response_serializer=motion__control__pb2.DroidStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'droidgrpc.EcatplatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('droidgrpc.EcatplatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EcatplatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetArmConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.EcatplatService/GetArmConfig',
            motion__control__pb2.Empty.SerializeToString,
            motion__control__pb2.DroidConfigs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLegConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.EcatplatService/GetLegConfig',
            motion__control__pb2.Empty.SerializeToString,
            motion__control__pb2.DroidConfigs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.EcatplatService/GetRobotConfig',
            motion__control__pb2.Empty.SerializeToString,
            motion__control__pb2.DroidConfigs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArmState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.EcatplatService/GetArmState',
            motion__control__pb2.Empty.SerializeToString,
            motion__control__pb2.DroidStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLegState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.EcatplatService/GetLegState',
            motion__control__pb2.Empty.SerializeToString,
            motion__control__pb2.DroidStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.EcatplatService/GetRobotState',
            motion__control__pb2.Empty.SerializeToString,
            motion__control__pb2.DroidStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArmStateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/droidgrpc.EcatplatService/GetArmStateStream',
            motion__control__pb2.Empty.SerializeToString,
            motion__control__pb2.DroidStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLegStateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/droidgrpc.EcatplatService/GetLegStateStream',
            motion__control__pb2.Empty.SerializeToString,
            motion__control__pb2.DroidStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotStateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/droidgrpc.EcatplatService/GetRobotStateStream',
            motion__control__pb2.Empty.SerializeToString,
            motion__control__pb2.DroidStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetArmCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.EcatplatService/SetArmCommand',
            motion__control__pb2.DroidCommandRequest.SerializeToString,
            motion__control__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLegCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.EcatplatService/SetLegCommand',
            motion__control__pb2.DroidCommandRequest.SerializeToString,
            motion__control__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRobotCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droidgrpc.EcatplatService/SetRobotCommand',
            motion__control__pb2.DroidCommandRequest.SerializeToString,
            motion__control__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetArmCommandStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/droidgrpc.EcatplatService/SetArmCommandStream',
            motion__control__pb2.DroidCommandRequest.SerializeToString,
            motion__control__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLegCommandStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/droidgrpc.EcatplatService/SetLegCommandStream',
            motion__control__pb2.DroidCommandRequest.SerializeToString,
            motion__control__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRobotCommandStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/droidgrpc.EcatplatService/SetRobotCommandStream',
            motion__control__pb2.DroidCommandRequest.SerializeToString,
            motion__control__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeArmControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/droidgrpc.EcatplatService/ExchangeArmControlStream',
            motion__control__pb2.DroidCommandRequest.SerializeToString,
            motion__control__pb2.DroidStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeLegControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/droidgrpc.EcatplatService/ExchangeLegControlStream',
            motion__control__pb2.DroidCommandRequest.SerializeToString,
            motion__control__pb2.DroidStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeRobotControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/droidgrpc.EcatplatService/ExchangeRobotControlStream',
            motion__control__pb2.DroidCommandRequest.SerializeToString,
            motion__control__pb2.DroidStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
